[project]
name = "datapulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.4",
    "pandas>=2.3.3",
    "polars>=1.37.1",
    "streamlit>=1.53.1",
]
