[theme]
primaryColor = "#00d1b2"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1f2937"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
